from pathlib import Path
from html import escape

ROOT = Path('/home/ai/stackpicks-sites/new-sites')
TAG = 'stackpicks02-20'
AUTHOR = 'Mara Ellis'

SITES = {
    'driveway-detail': {
        'brand':'Weekend Detail', 'niche':'DIY car care and detailing',
        'query':'best car detailing kit for beginners',
        'hero':'DIY car care that starts with the right tools—not a shelf full of bottles.',
        'intro':'If you are new to detailing, the hard part is not finding products. It is choosing a small, compatible kit that helps you clean safely, inflate a tire, and restore the details you can actually see. We built this guide around a beginner’s driveway workflow: wash, dry, interior, wheels, and emergency air.',
        'hero_img':'hero-car.svg', 'accent':'#c2410c', 'soft':'#fff7ed',
        'products':[
          ('AstroAI AIRUN H portable tire inflator','Best for a compact emergency-and-detailing kit','B07QR4Q42L','Battery-free 12V power keeps the tool simple to store in the car.','The corded format is less convenient away from a vehicle.','tire inflator'),
          ('CERAKOTE Ceramic Headlight Restoration Kit','Best for visibly cloudy headlights','B084RQKLV8','A focused restoration kit is easier to follow than assembling abrasives separately.','Restoration quality depends on preparation and even application.','headlight restoration'),
          ('Chemical Guys Total Interior Cleaner','Best for a one-bottle interior starting point','B071ZTPRJL','A general interior cleaner keeps the beginner workflow short.','A single cleaner is not a substitute for material-specific testing.','interior cleaner'),
          ('AstroAI digital tire pressure gauge with inflator','Best for repeatable tire checks','B07D3PVBJ4','A gauge plus inflator reduces the number of tools needed for routine checks.','Digital tools still need a stable valve connection and a charged display.','pressure gauge'),
          ('KMM handheld car vacuum and air duster','Best for crumbs and tight cabin gaps','B0BYD5XB67','A small vacuum is useful for seats, consoles, and vents before wiping.','Compact tools trade capacity for easier storage.','car vacuum'),
        ],
        'criteria':['safe surface order','tool storage','cord or battery constraints','beginner setup effort','return-policy questions'],
        'how':'We organized the shortlist around a repeatable driveway sequence. First remove loose debris, then work from cleaner surfaces to dirtier ones, keep wheel tools separate from paint tools, and finish with tire pressure. We did not hands-on test these products; product-specific details are limited to the dated public listing evidence supplied for this build.',
        'faq':[('Can I use one towel everywhere?','No. Keep separate towels for paint, glass, wheels, and interior work so grit and product residue do not travel.'),('Should I start with a pressure washer?','No. A beginner kit can start with hand tools and a hose. Add equipment only after the workflow is repeatable.'),('What is the first purchase?','Choose the tool that fixes your most immediate constraint: tire inflation, interior debris, cloudy headlights, or a complete wash routine.'),('How often should I check tire pressure?','Use the vehicle maker’s recommended interval and check when tires are cold; the correct number is vehicle-specific.'),('Are these products hands-on tested?','No. The shortlist is source-based and dated; we do not present public ratings or listing facts as personal testing.')],
    },
    'bay-two': {
        'brand':'Bay Two', 'niche':'Garage and workshop organization',
        'query':'best overhead garage storage rack',
        'hero':'A garage layout that puts heavy, awkward storage where it belongs.',
        'intro':'The right garage organizer is not the one with the longest feature list. It is the one that fits your ceiling, wall structure, tool habits, and actual load. This guide starts with the highest-friction decisions—overhead clearance, shelf depth, mounting, and access—before you buy.',
        'hero_img':'hero-garage.svg', 'accent':'#0f766e', 'soft':'#f0fdfa',
        'products':[
          ('FLEXIMOUNTS 4x8 overhead garage ceiling rack','Best for reclaiming ceiling volume','B0194R5BSA','A large overhead platform can turn unused ceiling space into a labeled storage zone.','Measure joist direction, vehicle clearance, and access before choosing a large rack.','overhead rack'),
          ('Amazon Basics 4-shelf steel wire storage shelves','Best for a flexible floor-standing zone','B09W2Y51TC','Open wire shelves make frequently used bins visible and adjustable.','A floor unit consumes footprint that may be needed for vehicle doors or work benches.','wire shelving'),
          ('FLEXIMOUNTS 2-pack garage wall shelving','Best for spreading storage across a wall','B01LYQGF4M','Two wall shelves can divide seasonal bins from daily tools.','Wall structure and fastener compatibility matter more than shelf count.','wall shelving'),
          ('Rubbermaid FastTrack wall mounted rail system','Best for a modular wall starter','B07ZJVG6D9','A rail-based system supports a changeable wall instead of a fixed pegboard layout.','Accessory compatibility should be checked before expanding the system.','wall rail'),
          ('POKIPO power tool organizer with charging station','Best for keeping cordless tools visible','B0DBHMY2T2','A dedicated charging area can reduce bench clutter and battery hunting.','Confirm tool dimensions and outlet placement before mounting.','power tool organizer'),
        ],
        'criteria':['ceiling and wall fit','load and fastener questions','daily access','footprint saved','expandability'],
        'how':'We compared the shortlist by the physical decisions that cause garage systems to fail: where the load transfers, whether a car door can still open, whether daily tools stay within reach, and whether the first unit creates a coherent zone. We did not hands-on test these products; we use only the supplied dated listing evidence and manufacturer/listing details that a buyer should recheck before ordering.',
        'faq':[('Should heavy bins go overhead?','Only when the rack, ceiling structure, fasteners, and access plan support them. Keep frequently handled or very heavy items at a safer reachable height.'),('How do I choose between wall and floor storage?','Use walls when floor clearance matters; use floor shelving when you need adjustable access without drilling into wall structure.'),('What should I measure first?','Measure ceiling height, joist direction, wall width, vehicle-door swing, and the largest bin you intend to store.'),('Is a larger rack always better?','No. A rack that blocks lighting, doors, or maintenance access creates a new problem. Match capacity to the zone.'),('Are these products hands-on tested?','No. This is source-based decision support, not a claim of personal testing or load certification.')],
    },
}

CSS = '''*{box-sizing:border-box}body{margin:0;background:{soft};color:#18312f;font:16px/1.65 system-ui,-apple-system,sans-serif}a{color:{accent}}.wrap{max-width:1120px;margin:auto;padding:0 22px 70px}.top{background:{accent};color:#fff;padding:10px;text-align:center;font-size:.88rem}.top a{color:#fff}.nav{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:24px 0;border-bottom:1px solid #18312f22}.navlinks{display:flex;gap:16px;flex-wrap:wrap}.brand{font-weight:800;color:#18312f;text-decoration:none}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:28px;align-items:center;padding:42px 0 24px}.hero img{width:100%;border-radius:22px;border:1px solid #18312f22;background:#fff}.eyebrow,.label{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:800;color:{accent}}h1{font-size:clamp(2.3rem,5vw,4.7rem);line-height:1.02;margin:12px 0}.lede{font-size:1.15rem;max-width:700px}.disclosure,.pick,.criteria,.method,.faq,.sources{background:#fff;border:1px solid #18312f1c;border-radius:18px;padding:22px;margin:20px 0}.disclosure{border-left:6px solid {accent}}.pick{display:grid;grid-template-columns:180px 1fr;gap:20px}.pick img{width:180px;height:130px;object-fit:cover;border-radius:12px;background:{soft}}.pick h3{margin:0;font-size:1.3rem}.tagline{font-weight:700}.reasons{display:grid;grid-template-columns:1fr 1fr;gap:14px}.reasons div{padding:12px;border-radius:12px;background:{soft}}.btn{display:inline-block;background:{accent};color:#fff;border-radius:999px;padding:10px 16px;text-decoration:none;font-weight:800}.table-wrap{overflow:auto}.table-wrap table{width:100%;border-collapse:collapse;background:#fff}.table-wrap th,.table-wrap td{padding:12px;border:1px solid #18312f22;text-align:left}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}.grid article{background:#fff;border:1px solid #18312f1c;border-radius:16px;padding:18px}.author{display:flex;gap:14px;align-items:center}.author img{width:70px;height:70px;border-radius:50%}footer{border-top:1px solid #18312f22;margin-top:35px;padding-top:20px}@media(max-width:760px){.hero{grid-template-columns:1fr}.pick{grid-template-columns:1fr}.pick img{width:100%;height:auto}.reasons{grid-template-columns:1fr}}'''

def svg(label, color):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 700"><rect width="1200" height="700" fill="{color}"/><circle cx="950" cy="170" r="120" fill="#ffffff33"/><path d="M90 560h1020" stroke="#fff" stroke-width="18" opacity=".8"/><rect x="170" y="310" width="280" height="180" rx="24" fill="#fff" opacity=".9"/><rect x="520" y="250" width="410" height="240" rx="24" fill="#fff" opacity=".75"/><text x="90" y="130" fill="#fff" font-family="system-ui" font-weight="700" font-size="48">{label}</text><text x="90" y="635" fill="#fff" font-family="system-ui" font-size="24">Original StackPicks illustration · not a retailer image</text></svg>'''

def page(site, root, title, body):
    css=CSS.replace('{soft}',site['soft']).replace('{accent}',site['accent'])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | {escape(site['brand'])}</title><meta name="description" content="Source-based {escape(site['niche'])} decision guide."><link rel="canonical" href="{root}index.html"><style>{css}</style></head><body><div class="top">As an Amazon Associate I earn from qualifying purchases. <a href="affiliate-disclosure.html">Affiliate disclosure</a></div><div class="wrap"><header class="nav"><a class="brand" href="index.html">{escape(site['brand'])}</a><nav class="navlinks"><a href="index.html">Guides</a><a href="about.html">How we picked</a><a href="affiliate-disclosure.html">Disclosure</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a></nav></header>{body}<footer><p><strong>{escape(site['brand'])}</strong> · independent comparison publishing.</p><div class="author"><img src="author.svg" alt="Headshot illustration of {AUTHOR}"><p><strong>Written by {AUTHOR}</strong><br>Editor focused on practical product decisions, source boundaries, and honest tradeoffs. Last updated September 11, 2026.</p></div><p><a href="affiliate-disclosure.html">Affiliate Disclosure</a> · <a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a> · <a href="mailto:stackpicksmedia@gmail.com">Contact</a></p></footer></div></body></html>'''

def build(slug,site):
    d=ROOT/slug; d.mkdir(parents=True,exist_ok=True)
    (d/'hero.svg').write_text(svg(site['brand'],site['accent']))
    (d/'author.svg').write_text(svg(AUTHOR,'#334155'))
    for i,p in enumerate(site['products'],1): (d/f'product-{i}.svg').write_text(svg(p[5].title(),site['accent']))
    cards=[]
    for i,(name,tagline,asin,why,limit,kind) in enumerate(site['products'],1):
        url=f'https://www.amazon.com/dp/{asin}/?tag={TAG}'
        cards.append(f'''<article class="pick" id="pick-{i}"><img src="product-{i}.svg" alt="Original illustration for {escape(name)}"><div><p class="label">{escape(kind)}</p><h3>{escape(name)}</h3><p class="tagline">{escape(tagline)}</p><p><strong>Why it belongs:</strong> {escape(why)}</p><div class="reasons"><div><strong>Choose it when</strong><br>{escape(why)}</div><div><strong>Watch the limit</strong><br>{escape(limit)}</div></div><p>Current price and availability: <strong>check the live Amazon listing</strong>.</p><a class="btn" data-umami-event="affiliate-click" data-product="{escape(asin)}" rel="sponsored nofollow" target="_blank" href="{url}">Check price at Amazon</a><p class="label">(paid link) · price and availability change; verify on Amazon</p></div></article>''')
    table=''.join(f'<tr><td>{escape(p[1])}</td><td>{escape(p[0])}</td><td>Product fit, dimensions, and live availability</td><td><a data-umami-event="affiliate-click" rel="sponsored nofollow" target="_blank" href="https://www.amazon.com/dp/{p[2]}/?tag={TAG}">Check price at Amazon</a></td></tr>' for p in site['products'])
    faq=''.join(f'<article><h3>{escape(q)}</h3><p>{escape(a)}</p></article>' for q,a in site['faq'])
    body=f'''<main><section class="hero"><div><p class="eyebrow">{escape(site['niche'])} · 2026 guide</p><h1>{escape(site['hero'])}</h1><p class="lede">{escape(site['intro'])}</p><p><a class="btn" href="#picks">Jump to the picks</a></p></div><img src="hero.svg" alt="Original {escape(site['brand'])} hero illustration"></section><section class="disclosure"><strong>Affiliate disclosure:</strong> As an Amazon Associate I earn from qualifying purchases. Buttons marked “(paid link)” may earn a commission at no extra cost to you.</section><section class="criteria"><p class="label">How to shop</p><div class="grid">{''.join(f'<article><strong>{escape(x.title())}</strong><br>Check this before treating a listing as a fit.</article>' for x in site['criteria'])}</div></section><section id="picks"><p class="eyebrow">Our shortlist</p><h2>The picks, by buyer type</h2><p>There is no universal winner. The best first choice depends on the constraint you are solving. Every link below goes to Amazon; price, availability, ratings, and seller information are intentionally left to the live listing rather than typed here.</p>{''.join(cards)}</section><section class="table-wrap"><h2>Quick comparison</h2><table><thead><tr><th>Buyer type</th><th>Pick</th><th>Decision check</th><th>Live price</th></tr></thead><tbody>{table}</tbody></table></section><section class="method"><h2>How we picked</h2><p>{escape(site['how'])}</p><p>Our method is source-based, not hands-on testing. The product set came from the dated research brief; recheck the live listing before purchase. We do not hand-type Amazon prices, ratings, review counts, or availability.</p></section><section><h2>FAQ</h2><div class="grid">{faq}</div></section><section class="sources"><h2>Also considered</h2><p>We excluded generic category roundups, products without a clear role in the workflow, and any listing fact that could not be rechecked. We would rather narrow the set than fill a comparison table with invented certainty.</p><p><strong>Sources:</strong> Amazon best-seller research captured September 11, 2026; Amazon live listing links above; Amazon Associates disclosure and link rules. Research boundary: no hands-on product testing.</p></section></main>'''
    (d/'index.html').write_text(page(site,'./',f"{site['query'].title()}",body))
    about='<main><p class="eyebrow">Method</p><h1>How {brand} researches</h1><section class="method"><p>We start with a concrete buyer problem, select comparable products from a dated research brief, and describe one reason to choose and one tradeoff for each. We do not invent prices, ratings, testing results, or availability. The live retailer listing is the source of truth for current purchase details.</p><h2>What we did not do</h2><p>We did not scrape Amazon images, claim hands-on testing, or turn marketplace signals into sales claims. Product photos on this page are original StackPicks illustrations, not retailer images.</p></section></main>'.replace('{brand}',escape(site['brand']))
    (d/'about.html').write_text(page(site,'./','How we picked',about))
    (d/'affiliate-disclosure.html').write_text(page(site,'./','Affiliate disclosure','<main><h1>Affiliate disclosure</h1><p>As an Amazon Associate I earn from qualifying purchases. A marked link may earn a commission at no extra cost to you. Editorial criteria and product tradeoffs are not changed by the relationship.</p></main>'))
    (d/'privacy.html').write_text(page(site,'./','Privacy','<main><h1>Privacy</h1><p>This static site does not provide accounts or forms. Basic server and analytics data may be processed to understand page visits and outbound button events. See the site operator for questions.</p></main>'))
    (d/'terms.html').write_text(page(site,'./','Terms','<main><h1>Terms</h1><p>Information is provided for general shopping research. Product prices, availability, specifications, and policies change. Verify current details with the retailer before buying.</p></main>'))
    (d/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://stackpicks.net/{slug}/{u}</loc></url>' for u in ['index.html','about.html','affiliate-disclosure.html','privacy.html','terms.html'])+'</urlset>')
    (d/'robots.txt').write_text('User-agent: *\nDisallow: /\n')

for slug,site in SITES.items(): build(slug,site)
print('built', ','.join(SITES))
